name: VOID PCB

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

jobs:
  KiBot-Generation:
    runs-on: ubuntu-latest  # Don't change
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate gerber for VOID Cherry MX reversible
      uses: INTI-CMNB/KiBot@v1.8.1
      with:
        config: .kibot.yaml
        dir: cherry-mx/gerber
        board: cherry-mx/void-cherry-mx.kicad_pcb
        schema: cherry-mx/void-cherry-mx.kicad_sch

    - name: Generate gerber for VOID Chocolate reversible
      uses: INTI-CMNB/KiBot@v1.8.1
      with:
        config: .kibot.yaml
        dir: chocolate/gerber
        board: chocolate/void-chocolate.kicad_pcb
        schema: chocolate/void-chocolate.kicad_sch

    - name: Generate gerber for VOID Cherry MX reversible
      uses: INTI-CMNB/KiBot@v1.8.1
      with:
        config: .kibot.yaml
        dir: hybrid-mx/gerber
        board: hybrid-mx/void-hybrid-mx.kicad_pcb
        schema: hybrid-mx/void-hybrid-mx.kicad_sch

    - name: Zip Gerber files
      run: |
          zip -r --junk-paths void-cherry-mx.zip cherry-mx/gerber
          zip -r --junk-paths void-chocolate.zip chocolate/gerber
          zip -r --junk-paths void-hybrid-mx.zip hybrid-mx/gerber

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: "*.zip"
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
